version: "~> 1.0"
language: rust
os:
- linux
- osx
- windows
rust:
- 1.40.0
- stable
- beta
- nightly
env:
  global:
  - RUSTFLAGS='-D warnings'
before_script:
- rustup component add clippy
- rustup component add rustfmt

after_script:
- cargo install cargo-cache --no-default-features --features ci-autoclean cargo-cache
- cargo-cache

script:
- echo "Rust version $TRAVIS_RUST_VERSION"
- cargo build --verbose
- if [ $TRAVIS_RUST_VERSION != "1.40.0" ]; then
    cargo clippy --verbose --all-targets --all-features -- -D warnings;
  fi
- cargo fmt --all -- --check
- cargo test --verbose --no-default-features
- cargo test --verbose --no-default-features --features "rand"
- cargo test --verbose --no-default-features --features "chrono"
- cargo test --verbose --no-default-features --features "serde"
- cargo test --verbose --no-default-features --features "chrono rand serde"
- cargo test --verbose --no-default-features --features "chrono rand doc-comment serde"
- cargo test --verbose
- cargo doc
jobs:
  fast_finish: true
  allow_failures:
  - rust: nightly
cache: cargo
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
after_success: |
  [ $TRAVIS_OS_NAME = linux ] &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/rusty_ulid-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
notifications:
  pushover:
    api_key:
      secure: JYI2eD4UzVafS37hOyvFVwDoKcvq9fMB3FHSYnt06yfmASfmppxi6PbHgo9J9+UMeW88sy4AByeV+oyNMiWzlC38GfWFi+S0L/EzpNJzV45WJMyNmK1YGxoKAvcyfNDLoMU6B9XBMvmLyH5CEgkOks3ADuSRDh2eulWQC9Qcts97O7NzE0S/lRmtQeGRT2k65xleRgscdR7+KtcMMBa9Mh7ImQ3hFhbaz9aNaYiiseSivF8eWHd/qQtwqTtn7mHRV7B5iFTyVh8nR7PpnrSRO1ro+KtMNlsHywmYc85rfBhHXY4rQH0ZwMH9W3Sy0PJZw39DOY9pDrkfWpSY7KMmELp9oFrAuyYMXmQj5OcUn2rPZpOZ6ZuMH1C6XbFAhVK8TBt0jJ13+Jbkj86STk/cBTDL/e/lVgS6NvfbkHKH2suux3jbCCC5CumH8urUgwkJQ2knqTVuK7wa9zkk2i7KaMMT9Jk3V+VihJTsFqVBvU2oGqxAONGXXkV/bV1bh34dOCJVIY9wWKJFZOhK5JY1UMQE+zeav9Wo2DN0+mbILl7r6LCon5rARf+2XPmB682kfSJmm1jQ91T4hgUaN9JCW+cZrDb5oH4qtShkMJqeALeVfbaasakuWvUsCVme+PFwYVmxWE+eUqw2vW1Ji5AjyCBArwmA9R3FX4Ali3XObJM=
    users:
      secure: F3bhaWz6bn1JadRcVVZyAeVOCcNQ+yNKTSbwkY/mSBiHE2XuhynIdqN40zEeECmT0Wsm7vtJ4KwyIQb+T/ymTjhfdw2/lj79GY4Y1aIyvokHmoHewGHrhcq0f1a1WYe6OtfQd6Vy0CC2kjIW9Fxuv5O6+9BzRy152bQal7UpuN2CKbnLZCbPivVMCkBex8w6mRTIfr4qmuQbY+oCiZIsi8510QIFUt2VteCZJr2Sol+l3cIeB2qpkDgkyAmUfV4fPBAiMGQneDKxwUNcqtGBmq7JEfemtVkWjcOobaQ0bhYoQOTe6LI55t3fVQ1H65bgvwVRQ56TwVMFA8PIv0TAGP6SVsrP3y2rup5RNoChzdBH0yl2eISKpFx/1NMNwrG+pl40v46IAewywynVoBQ3mU0YyfGlEfr4PkM1WFC/MY6jDVjGcpad35EqHwuDnBCokw0BTK0BM+xhJr3TfTZkDG+hhlaOx1evHNTQMZoIL7JsaQPWp1QMPaVEO9czlPsZTvOGKLmFpNVSH5IBmxJKrXGFEUzC1irnc+6q0vT8UT3UuEygwt/gwxqy69qFCLKzaBKppFTkdiOgVxgZNy8BuM8ivFlYVqOacNXQSOQ8Yw0JcChN701uwAEeUf72NA1L35oNO3TOgniuyQUOJVy2mjFUHYTl6OtDCns3WiZ0kws=
